# -*- coding: utf-8 -*-
"""DöngülerÖdev.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pEuoXzAwGYNFMugU4TYtGHA1w5t8TklG
"""

#Problem 1

for i in range(100000):
    sayac = 0
    for j in range(1,i):
        if i % j ==0:
            sayac += j
    if sayac == i:
        print(i)   

#Problem 2

sayı = input("Sayı:")
basamak_sayisi = len(sayı)
sayı = int(sayı)
basamak = 0
toplam = 0

gecici_sayı = sayı

while (gecici_sayı > 0):
    
    basamak = gecici_sayı % 10
    
    toplam += basamak ** basamak_sayisi
    
    gecici_sayı //= 10
if (toplam == sayı):
    print(sayı,"bir armstrong sayısıdır.")
else:
    print(sayı,"bir armstrong sayısı değildir.")
print(basamak_sayisi)

#Problem 3

for i in range(11):
  for j in range(11):
    print("{} x {} = {}".format(i,j,i*j))
  print("\n")

#Problem 4

toplam = 0

while True:
    
    sayı = input("Sayı:")
    
    if (sayı == "q"):
        break
    sayı = int(sayı)
    
    toplam += sayı
    
print("Girdiğiniz Sayıların Toplamı:",toplam)

#Problem 5

for i in range(1,100):
  if i % 3 == 0:
    print(i)
  else:
    continue


#Problem 6

liste = [x for i in range(1,101) if i % 2 == 0]
print(liste)