# -*- coding: utf-8 -*-
"""FonksiyonlarOdev.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pEuoXzAwGYNFMugU4TYtGHA1w5t8TklG
"""

def mukemmel_sayi(sayi):
    temp = 0
    for i in range(1,sayi):
        if sayi%i==0:
            temp+=i
    return sayi == temp
for i in range(1,1001):
    if mukemmel_sayi(i):
        print(i,"Mükemmel Sayıdır.")

#Problem 2

def obeb_bul(a,b):
    obeb = 1
    x = 1
    while x<=a and x<=b:
        if not(a%x) and not(b%x):
            obeb = x
        x+=1
    return obeb
sayi1 = int(input("Birinci sayi: "))
sayi2 = int(input("İkinci sayi: "))
print(obeb_bul(sayi1,sayi2))

#Problem 3

def okek_bul(a,b):
    okek = 1
    y = 2
    while True:
        if a % y == 0 and b % y == 0:
            okek *= y
            a //= y
            b //= y
        elif a % y == 0 and b % y != 0:
            okek *= y
            a//=y
        elif a % y != 0 and b % y == 0:
            okek *= y
            b//=y
        else:
            y+=1
        if a == 1 and b == 1:
            break
    return okek

sayi1 = int(input("Birinci sayi: "))
sayi2 = int(input("İkinci sayi: "))
print(okek_bul(sayi1,sayi2))


#Problem 4

def sayi_soyle(x):
    onlar_basamagi = x // 10
    birler_basamagi = x % 10
    onlar = {0:" ",1:"On",2:"Yirmi",3:"Otuz",4:"Kırk",5:"Elli",6:"Altmış",7:"Yetmiş",8:"Seksen",9:"Doksan"}
    birler = {0:" ",1:"Bir",2:"İki",3:"Üç",4:"Dört",5:"Beş",6:"Altı",7:"Yedi",8:"Sekiz",9:"Dokuz"}
    return onlar[onlar_basamagi]+" "+birler[birler_basamagi]
sayi = int(input("Sayiyi giriniz..."))
print(sayi_soyle(sayi))

#Problem 5

def pisagor_bulma():
    
    pisagor_listesi = list()
    for i in range(1,101):
        for j in range(1,101):
            c = (i ** 2 + j ** 2) ** 0.5
            if (c == int(c) ):
                pisagor_listesi.append((i,j,int(c)))
    return pisagor_listesi
for i in pisagor_bulma():
    print(i)